[project]
site_url = "https://bogdan-glitchm.github.io/RoValra-CD/"
site_name = "RoValra Contributor Documentation"
site_description = "By contributors, for new contributors"
site_author = "bogdan-glitchm and RoValra contributors"

copyright = "Copyright &copy; 2026 Bogdan and other RoValra contributors."

repo_url = "https://github.com/bogdan-glitchm/RoValra-CD"
repo_name = "bogdan-glitchm/RoValra-CD"
# edit_uri = "edit/main/docs/"

nav = [
  { "RoValra Contributor Docs" = "index.md" },

  { "Contributions" = [
    { "Adding yourself" = "contributors/adding-yourself.md" }
  
  ] },

  { "Reading Settings" = [
    "reading-settings/unified.md",
    "reading-settings/chrome-storage.md",
    "reading-settings/load-settings.md",
  ] },

  { "Locales" = [
    "locales/reading-locale.md",
    "locales/adding-locale.md"
  ]},

  { "Icons" = [
    "icons/icons-in-html.md",
    "icons/icons-in-js.md"
  ]},

  {"Terms of Service" = [
    "tos/license.md",
    "tos/privacy-policy.md",
    "tos/api-tos.md",
    "tos/api-privacy-policy.md"
  ]}
]

extra_css = ["style/icons.css"]
# extra_javascript = ["javascripts/extra.js"]

dev_addr = "0.0.0.0:8000"

[project.theme]
# variant = "classic"
custom_dir = "overrides"
# favicon = "images/favicon.png"
language = "en"
features = [
  "announce.dismiss",
  "content.action.edit",
  # "content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  # "header.autohide",
  # "navigation.expand",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.instant.progress",
  "navigation.path",
  # "navigation.prune",
  "navigation.sections",
  # "navigation.tabs",
  # "navigation.tabs.sticky",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  # "toc.follow",
  # "toc.integrate",
]

# logo = "assets/logo.png"

# [project.theme.icon]
# logo = "lucide/smile"

# [project.theme.font]
# text = "Inter"
# code = "Jetbrains Mono"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

# [[project.extra.social]]
# icon = "fontawesome/brands/github"
# link = "https://github.com/user/repo"

# [[project.extra.social]]
# icon = "fontawesome/brands/mastodon"
# link = "https://fosstodon.org/@user"

[project.markdown_extensions]
abbr = {}
admonition = {}
attr_list = {}
def_list = {}
footnotes = {}
md_in_html = {}
toc.permalink = true
pymdownx.arithmatex.generic = true
pymdownx.betterem = {}
pymdownx.caret = {}
pymdownx.details = {}
pymdownx.emoji.emoji_generator = "zensical.extensions.emoji.to_svg"
pymdownx.emoji.emoji_index = "zensical.extensions.emoji.twemoji"
pymdownx.highlight.anchor_linenums = true
pymdownx.highlight.line_spans = "__span"
pymdownx.highlight.pygments_lang_class = true
pymdownx.inlinehilite = {}
pymdownx.keys = {}
pymdownx.magiclink = {}
pymdownx.mark = {}
pymdownx.smartsymbols = {}
# pymdownx.snippets.base_path = "includes"
pymdownx.snippets = { base_path = "reference" }
pymdownx.superfences.custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
]
pymdownx.tabbed.alternate_style = true
pymdownx.tabbed.combine_header_slug = true
pymdownx.tasklist.custom_checkbox = true
pymdownx.tilde = {}

[project.extra.status]
risky = "Dangerous"
slow = "Slow / Unoptimized"
new = "New"
deprecated = "Deprecated"
construction = "Under Construction"

[project.extra.analytics.feedback]
title = "Was this page helpful?"

[[project.extra.analytics.feedback.ratings]]
icon = "material/emoticon-happy-outline"
name = "This page was helpful"
data = 1
note = "Thanks for your feedback!"

[[project.extra.analytics.feedback.ratings]]
icon = "material/emoticon-sad-outline"
name = "This page could be improved"
data = 0
note = """
  Thanks for your feedback! Help us improve this page by
  using our <a href="../..." target="_blank" rel="noopener">feedback form</a>.
"""

[project.extra.consent]
actions = [
  "accept",
  "manage", 
]

[project.extra.analytics]
provider = "google"
property = "G-K8EYL52MCX"

[project.theme.icon]
repo = "fontawesome/brands/github"

[project.extra.tags]
Settings = "settings"
Icons = "icons"
HTML = "html"
Credit = "credit"
Contributors = "contributors"
Translators = "translators"
Legal = "legal"
Backend = "backend"
GDPR = "gdpr"
UI = "ui"
Strings = "Strings"

[project.theme.icon.tag]
default = "lucide/hash"
settings = "custom/settings"
icons = "custom/icons"
html = "custom/html"

[project.markdown_extensions.pymdownx.emoji.options]
custom_icons = ["overrides/.icons"]
